trigger:
- main

pool:
  name: dhurander

stages:
- stage: terraform
  displayName: Terraform
  jobs:
  - job: terraform_job
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infradev'
        backendServiceArm: 'trvy'
        backendAzureRmStorageAccountName: 'azpipeline123'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'prod.terraform.tfstate'
    -  script: 
          terraform version
          terraform providers
          displayName:'Check Terraform and AzureRM Provider'
      
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infradev'